import {
  Card,
  CardBody,
  CardHeader,
  Heading,
  Stat,
  StatGroup,
  StatLabel,
  StatNumber,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
} from "@chakra-ui/react";
import { AnnotationResult } from "../interfaces/annotation-result";

// TODO: Extract components!

export default function RelationMetrics({
  annotationResult,
}: {
  annotationResult: AnnotationResult;
}) {
  return (
    <Card mt={4}>
      <CardHeader>
        <Heading size="md">Relation metrics</Heading>
      </CardHeader>
      <CardBody>
        <Tabs variant="enclosed" colorScheme="teal">
          <TabList marginBottom={2}>
            <Tab>Overall</Tab>
            <Tab>Actor Performer</Tab>
            <Tab>Actor Recipient</Tab>
            <Tab>Flow</Tab>
            <Tab>Further Specification</Tab>
            <Tab>Condition Specification</Tab>
          </TabList>
          <TabPanels>
            <TabPanel>
              <StatGroup>
                <Stat>
                  <StatLabel>F1-Score</StatLabel>
                  <StatNumber>
                    {annotationResult.overall_relation.f1_score}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Recall</StatLabel>
                  <StatNumber>
                    {annotationResult.overall_relation.recall}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Precision</StatLabel>
                  <StatNumber>
                    {annotationResult.overall_relation.precision}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Absolute</StatLabel>
                  <StatNumber>
                    {annotationResult.overall_relation.true_positives}/
                    {annotationResult.overall_relation.reference_count}
                  </StatNumber>
                </Stat>
              </StatGroup>
            </TabPanel>
            <TabPanel>
              <StatGroup>
                <Stat>
                  <StatLabel>F1-Score</StatLabel>
                  <StatNumber>
                    {annotationResult.actor_performer.f1_score}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Recall</StatLabel>
                  <StatNumber>
                    {annotationResult.actor_performer.recall}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Precision</StatLabel>
                  <StatNumber>
                    {annotationResult.actor_performer.precision}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Absolute</StatLabel>
                  <StatNumber>
                    {annotationResult.actor_performer.true_positives}/
                    {annotationResult.actor_performer.reference_count}
                  </StatNumber>
                </Stat>
              </StatGroup>
            </TabPanel>
            <TabPanel>
              <StatGroup>
                <Stat>
                  <StatLabel>F1-Score</StatLabel>
                  <StatNumber>
                    {annotationResult.actor_recipient.f1_score}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Recall</StatLabel>
                  <StatNumber>
                    {annotationResult.actor_recipient.recall}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Precision</StatLabel>
                  <StatNumber>
                    {annotationResult.actor_recipient.precision}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Absolute</StatLabel>
                  <StatNumber>
                    {annotationResult.actor_recipient.true_positives}/
                    {annotationResult.actor_recipient.reference_count}
                  </StatNumber>
                </Stat>
              </StatGroup>
            </TabPanel>
            <TabPanel>
              <StatGroup>
                <Stat>
                  <StatLabel>F1-Score</StatLabel>
                  <StatNumber>{annotationResult.flow.f1_score}</StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Recall</StatLabel>
                  <StatNumber>{annotationResult.flow.recall}</StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Precision</StatLabel>
                  <StatNumber>{annotationResult.flow.precision}</StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Absolute</StatLabel>
                  <StatNumber>
                    {annotationResult.flow.true_positives}/
                    {annotationResult.flow.reference_count}
                  </StatNumber>
                </Stat>
              </StatGroup>
            </TabPanel>
            <TabPanel>
              <StatGroup>
                <Stat>
                  <StatLabel>F1-Score</StatLabel>
                  <StatNumber>
                    {annotationResult.further_specification_relation.f1_score}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Recall</StatLabel>
                  <StatNumber>
                    {annotationResult.further_specification_relation.recall}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Precision</StatLabel>
                  <StatNumber>
                    {annotationResult.further_specification_relation.precision}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Absolute</StatLabel>
                  <StatNumber>
                    {
                      annotationResult.further_specification_relation
                        .true_positives
                    }
                    /
                    {
                      annotationResult.further_specification_relation
                        .reference_count
                    }
                  </StatNumber>
                </Stat>
              </StatGroup>
            </TabPanel>
            <TabPanel>
              <StatGroup>
                <Stat>
                  <StatLabel>F1-Score</StatLabel>
                  <StatNumber>
                    {annotationResult.condition_specification.f1_score}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Recall</StatLabel>
                  <StatNumber>
                    {annotationResult.condition_specification.recall}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Precision</StatLabel>
                  <StatNumber>
                    {annotationResult.condition_specification.precision}
                  </StatNumber>
                </Stat>
                <Stat>
                  <StatLabel>Absolute</StatLabel>
                  <StatNumber>
                    {annotationResult.condition_specification.true_positives}/
                    {annotationResult.condition_specification.reference_count}
                  </StatNumber>
                </Stat>
              </StatGroup>
            </TabPanel>
          </TabPanels>
        </Tabs>
      </CardBody>
    </Card>
  );
}
